version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fa:7b:b1:88:ba:c3:08:c0:15:cd:ef:f8:3a:7a:d2:e3"
      - checkout
      - restore_cache:
          keys:
            - dependencies_notes
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_notes
      - run:
          name: Build
          command: yarn docs:build
      - run:
          name: Prepare shell commands
          # shell chmod +x 赋予执行权限
          # 执行shell脚本
          command: chmod +x scripts/deploy.sh
      - run:
          name: Run Deploy to Github pages
          command: ./scripts/deploy.sh
